CREATE TABLE head (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  profile_pic TEXT,
  name VARCHAR(255) NOT NULL,
  role role_type DEFAULT 'head',
  created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);